const translations = {
  fr: {
    'Home': 'Accueil',
    'About Us': 'À propos',
    'Products': 'Produits',
    'Contact': 'Contact',
    'REQUEST A QUOTE': 'DEMANDER UN DEVIS',
    'Request a Quote': 'Demander un devis',
    'EXPLORE OUR PRODUCTS': 'DÉCOUVRIR NOS PRODUITS',
    'Explore Our Products': 'Découvrir nos produits',
    'VIEW DETAILS': 'VOIR LES DÉTAILS',
    'View details': 'Voir les détails',
    'LEARN MORE': 'EN SAVOIR PLUS',
    'CONTACT US': 'NOUS CONTACTER',
    'OUR PROMISE': 'NOTRE PROMESSE',
    'Quality rooted in Tunisia': 'Une qualité enracinée en Tunisie',
    'Ben Laribi Dattes brings carefully selected Deglet Nour dates to the global market with attention to origin, quality and export readiness.': 'Ben Laribi Dattes propose au marché mondial des dattes Deglet Nour soigneusement sélectionnées, avec une attention particulière à leur origine, leur qualité et leur préparation à l’export.',
    'OUR PRODUCTS': 'NOS PRODUITS',
    'Our product categories': 'Nos catégories de produits',
    'Dates': 'Dattes',
    'Fruits': 'Fruits',
    'Vegetables': 'Légumes',
    'View category': 'Voir la catégorie',
    'TUNISIAN DATES': 'DATTES TUNISIENNES',
    'Discover the richness of Tunisian dates': 'Découvrez la richesse des dattes tunisiennes',
    'OUR PROCESS': 'NOTRE PROCESSUS',
    'From selection to export': 'De la sélection à l’export',
    'From Tunisia to the world': 'De la Tunisie au monde',
    'Built for professional markets': 'Conçu pour les marchés professionnels',
    'ABOUT US': 'À PROPOS DE NOUS',
    'WHO WE ARE': 'QUI SOMMES-NOUS',
    'OUR MISSION': 'NOTRE MISSION',
    'OUR VISION': 'NOTRE VISION',
    'OUR VALUES': 'NOS VALEURS',
    'OUR EXPERTISE': 'NOTRE EXPERTISE',
    'OUR COMMITMENT': 'NOTRE ENGAGEMENT',
    'CONTACT': 'CONTACT',
    'RELATED PRODUCTS': 'PRODUITS ASSOCIÉS',
    'Who we are': 'Qui sommes-nous',
    'Our mission': 'Notre mission',
    'Our vision': 'Notre vision',
    'Our values': 'Nos valeurs',
    'Our expertise': 'Notre expertise',
    'Our commitment': 'Notre engagement',
    'Premium Quality': 'Qualité supérieure',
    'Natural Origin': 'Origine naturelle',
    'Export Focus': 'Orientation export',
    'Branched Dates': 'Dattes branchées',
    'Standard Dates': 'Dattes standard',
    'Packaged Dates': 'Dattes emballées',
    'Quality': 'Qualité',
    'Reliability': 'Fiabilité',
    'Authenticity': 'Authenticité',
    'Transparency': 'Transparence',
    'Customer Focus': 'Orientation client',
    'Tunisian heritage': 'Patrimoine tunisien',
    'Company': 'Entreprise',
    'Support': 'Assistance',
    'Privacy Policy': 'Politique de confidentialité',
    'Terms & Conditions': 'Termes et conditions',
    'Terms': 'Termes',
    'Contact Us': 'Contactez-nous',
    "FROM TUNISIA'S FINEST LANDS TO THE WORLD": 'DES MEILLEURES TERRES DE TUNISIE AU MONDE',
    'We select, prepare and export quality Tunisian dates, fruits and vegetables for professional and international partners.': 'Nous sélectionnons, préparons et exportons des dattes, fruits et légumes tunisiens de qualité pour des partenaires professionnels et internationaux.',
    'Ben Laribi Dattes brings carefully selected agricultural products to the global market with attention to origin, quality and export readiness.': 'Ben Laribi Dattes propose au marché mondial des produits agricoles soigneusement sélectionnés, avec une attention particulière à leur origine, leur qualité et leur préparation à l’export.',
    'Strict selection and professional handling to match export expectations.': 'Une sélection rigoureuse et une manipulation professionnelle pour répondre aux exigences de l’export.',
    "Products rooted in Tunisia's agricultural heritage and Mediterranean climate.": 'Des produits issus du patrimoine agricole tunisien et du climat méditerranéen.',
    'Professional preparation and communication designed for international trade.': 'Une préparation et une communication professionnelles adaptées au commerce international.',
    "Signature varieties reflecting Tunisia's rich palm heritage and export expertise.": 'Des variétés emblématiques qui reflètent le riche patrimoine oasien tunisien et notre expertise à l’export.',
    'Selected fruit varieties prepared for professional packaging and distribution.': 'Des variétés de fruits sélectionnées et préparées pour un emballage et une distribution professionnels.',
    'Fresh, carefully selected vegetables produced for international buyers.': 'Des légumes frais soigneusement sélectionnés pour les acheteurs internationaux.',
    'From carefully selected dates to export-ready preparation, our products combine tradition and commercial reliability.': 'De la sélection des dattes à leur préparation pour l’export, nos produits associent tradition et fiabilité commerciale.',
    'Natural presentation with premium appeal and distinctive clusters.': 'Une présentation naturelle, élégante et caractérisée par de belles grappes.',
    'Reliable quality suited to professional trade and export requirements.': 'Une qualité fiable adaptée au commerce professionnel et aux exigences de l’export.',
    'Presentation-focused solutions created for professional markets.': 'Des solutions axées sur la présentation, conçues pour les marchés professionnels.',
    'Selection': 'Sélection',
    'Meticulous picking and grading according to market and customer requirements.': 'Une récolte et un calibrage minutieux selon les exigences du marché et des clients.',
    'Quality Control': 'Contrôle qualité',
    'Inspection and controls throughout preparation to support consistency.': 'Des inspections et contrôles tout au long de la préparation pour garantir la régularité.',
    'Preparation': 'Préparation',
    'Sorting, cleaning and conditioning according to packaging and market needs.': 'Tri, nettoyage et conditionnement selon les besoins de l’emballage et du marché.',
    'Packaging': 'Emballage',
    'Flexible solutions that respect product integrity and presentation.': 'Des solutions flexibles qui préservent l’intégrité et la présentation du produit.',
    'Export': 'Export',
    'Documentation coordination and shipment support for international trade.': 'Coordination documentaire et accompagnement des expéditions pour le commerce international.',
    "Tunisia's agricultural traditions, oasis landscapes and climate create exceptional fruit and date varieties. Ben Laribi Dattes works with this heritage to deliver premium products suited to international trade.": 'Les traditions agricoles, les paysages oasiens et le climat tunisien donnent naissance à des fruits et des dattes d’exception. Ben Laribi Dattes s’appuie sur ce patrimoine pour proposer des produits premium adaptés au commerce international.',
    'We support product selection, packaging, customer communication and export preparation for professional buyers and partners. Our work is built around reliability, consistency and long-term relationships.': 'Nous accompagnons la sélection des produits, l’emballage, la communication client et la préparation à l’export pour les acheteurs et partenaires professionnels. Notre travail repose sur la fiabilité, la régularité et les relations durables.',
    'DISCUSS YOUR REQUIREMENTS': 'PARLONS DE VOS BESOINS',
    'We select, prepare and export premium Deglet Nour dates in professional formats for international partners.': 'Nous sélectionnons, préparons et exportons des dattes Deglet Nour premium dans des formats professionnels pour des partenaires internationaux.',
    'Deglet Nour dates prepared in professional formats for retail, wholesale and international markets.': 'Des dattes Deglet Nour préparées dans des formats professionnels pour les marchés du détail, de gros et internationaux.',
    'About Ben Laribi Dattes': 'À propos de Ben Laribi Dattes',
    'Rooted in Tunisia. Focused on quality. Connected to the world.': 'Ancrés en Tunisie. Attachés à la qualité. Ouverts sur le monde.',
    'Ben Laribi Dattes is a Tunisian agricultural export-focused company serving professional buyers seeking selected dates, fruits and vegetables. We work with the value of Tunisia\'s agricultural heritage while meeting the standards expected by modern international markets.': 'Ben Laribi Dattes est une entreprise tunisienne spécialisée dans l’exportation agricole, au service d’acheteurs professionnels à la recherche de dattes, fruits et légumes sélectionnés. Nous valorisons le patrimoine agricole tunisien tout en répondant aux standards des marchés internationaux modernes.',
    'Ben Laribi Dattes is a Tunisian agricultural export-focused company serving professional buyers seeking selected Deglet Nour dates. We work with the value of Tunisia\'s agricultural heritage while meeting the standards expected by modern international markets.': 'Ben Laribi Dattes est une entreprise tunisienne spécialisée dans l’exportation agricole, au service d’acheteurs professionnels à la recherche de dattes Deglet Nour sélectionnées. Nous valorisons le patrimoine agricole tunisien tout en répondant aux standards des marchés internationaux modernes.',
    'To deliver selected Tunisian agricultural products with care, consistency and professionalism to international buyers.': 'Proposer aux acheteurs internationaux des produits agricoles tunisiens sélectionnés avec soin, régularité et professionnalisme.',
    'To build trusted partnerships based on quality, transparency and long-term export cooperation.': 'Construire des partenariats de confiance fondés sur la qualité, la transparence et une coopération durable à l’export.',
    'Product selection and handling with attention to detail.': 'Une sélection et une manipulation des produits avec une grande attention aux détails.',
    'Professional communication and consistent processes.': 'Une communication professionnelle et des processus réguliers.',
    'Transparent product identity and honest sourcing.': 'Une identité produit transparente et un approvisionnement honnête.',
    'Open communication around requirements, conditions and preparation.': 'Une communication ouverte sur les exigences, les conditions et la préparation.',
    'Solutions created around buyer needs and market expectations.': 'Des solutions conçues autour des besoins des acheteurs et des attentes du marché.',
    'Rooted in the landscapes and agricultural traditions of Tunisia.': 'Ancrés dans les paysages et les traditions agricoles de la Tunisie.',
    'Our expertise covers selection, preparation, packaging and export coordination across date, fruit and vegetable categories. We support customers with a practical and professional approach.': 'Notre expertise couvre la sélection, la préparation, l’emballage et la coordination de l’export pour les dattes, fruits et légumes. Nous accompagnons nos clients avec une approche pratique et professionnelle.',
    'Product selection and grading': 'Sélection et calibrage des produits',
    'Packaging preparation for professional markets': 'Préparation des emballages pour les marchés professionnels',
    'Export-oriented communication': 'Communication orientée vers l’export',
    'Long-term commercial partnership support': 'Accompagnement des partenariats commerciaux durables',
    'We are committed to working with professionalism, care and respect for each market requirement while preserving the identity of Tunisia\'s agricultural excellence.': 'Nous nous engageons à travailler avec professionnalisme, soin et respect de chaque exigence du marché, tout en préservant l’identité de l’excellence agricole tunisienne.',
    "Let's work together": 'Travaillons ensemble',
    'Contact Ben Laribi Dattes for product information, export inquiries and partnership opportunities.': 'Contactez Ben Laribi Dattes pour obtenir des informations sur nos produits, vos demandes d’export et les possibilités de partenariat.',
    'Contact information': 'Informations de contact',
    'Phone:': 'Téléphone :',
    'Email:': 'E-mail :',
    'Address:': 'Adresse :',
    'Business hours:': 'Horaires :',
    'MAP LOCATION': 'LOCALISATION',
    'First Name *': 'Prénom *',
    'Last Name *': 'Nom *',
    'Company': 'Entreprise',
    'Email *': 'E-mail *',
    'Phone': 'Téléphone',
    'Country': 'Pays',
    'Product': 'Produit',
    'Quantity': 'Quantité',
    'Packaging': 'Emballage',
    'Message *': 'Message *',
    'SEND INQUIRY': 'ENVOYER LA DEMANDE',
    'CATALOG': 'CATALOGUE',
    'Our product catalog': 'Notre catalogue de produits',
    "Tunisia's agricultural excellence for professional and international markets.": 'L’excellence agricole tunisienne pour les marchés professionnels et internationaux.',
    'All': 'Tous',
    'Clear Search': 'Effacer la recherche',
    'No products found.': 'Aucun produit trouvé.',
    'Try another search term or select a different category.': 'Essayez un autre terme de recherche ou choisissez une autre catégorie.',
    'Please complete all required fields.': 'Veuillez remplir tous les champs obligatoires.',
    'Please provide a valid email address.': 'Veuillez fournir une adresse e-mail valide.',
    'Please provide a valid phone number.': 'Veuillez fournir un numéro de téléphone valide.',
    'Message must be at least 10 characters long.': 'Le message doit contenir au moins 10 caractères.',
    'Submitting inquiry…': 'Envoi de la demande…',
    'This demo form is not connected to a backend. Configure an API endpoint or email handler to enable live submissions.': 'Ce formulaire de démonstration n’est pas connecté à un serveur. Configurez une API ou un gestionnaire d’e-mails pour activer les envois.',
    'This website is designed as a static informational site. We do not collect personal information unless a visitor voluntarily submits data through a contact form or inquiry request.': 'Ce site est conçu comme un site informatif statique. Nous ne collectons pas d’informations personnelles sauf si un visiteur les envoie volontairement via un formulaire de contact ou une demande.',
    'Any information submitted through the contact form is used solely for inquiry handling and communication related to products or services. If a backend is later connected, data handling rules should be updated in accordance with applicable laws and regulations.': 'Toute information envoyée via le formulaire de contact est utilisée uniquement pour traiter les demandes et communiquer au sujet des produits ou services. Si un serveur est connecté ultérieurement, les règles de traitement des données devront être mises à jour conformément aux lois et réglementations applicables.',
    'Cookies may be added later for analytics or site functionality. Any future implementation should be disclosed clearly and configured responsibly.': 'Des cookies pourront être ajoutés ultérieurement pour l’analyse ou les fonctionnalités du site. Toute future mise en œuvre devra être clairement indiquée et configurée de manière responsable.',
    'These terms govern use of the Ben Laribi Dattes website for informational purposes. The website should be considered a representation of our commercial activities and product information.': 'Ces conditions régissent l’utilisation du site Ben Laribi Dattes à des fins informatives. Le site doit être considéré comme une présentation de nos activités commerciales et de nos informations produits.',
    'All product and business details should be confirmed through direct communication with the company, especially for commercial quantities, specifications and export requirements.': 'Tous les détails concernant les produits et l’activité doivent être confirmés par communication directe avec l’entreprise, notamment pour les quantités commerciales, les spécifications et les exigences d’export.',
    'Origin:': 'Origine :',
    'Packaging:': 'Emballage :',
    'Available according to requirements': 'Disponible selon les exigences',
    'Flexible according to customer need': 'Flexible selon les besoins du client',
    'standard': 'standard',
    'branched': 'branchée',
    'packaged': 'emballée',
    'fresh': 'frais',
    'conditioned': 'conditionnée',
    'loose': 'en vrac',
    'Branched': 'Branchées',
    'Conditioned': 'Conditionnées',
    'Loose': 'En vrac',
    'Deglet Nour Branched Bouquet 500g': 'Bouquet de dattes Deglet Nour branchées 500g',
    'Deglet Nour Branched Bouquet 250g': 'Bouquet de dattes Deglet Nour branchées 250g',
    'Deglet Nour Branched Tray': 'Barquette de dattes Deglet Nour branchées',
    'Deglet Nour Branched Paper Box': 'Carton papier de dattes Deglet Nour branchées',
    'Deglet Nour Branched Imen Box': 'Carton Imen de dattes Deglet Nour branchées',
    'Deglet Nour Branched Export Box': 'Carton export de dattes Deglet Nour branchées',
    'Deglet Nour Conditioned Tray 200g': 'Barquette de dattes Deglet Nour conditionnées 200g',
    'Deglet Nour Conditioned Retail Packs': 'Packs de dattes Deglet Nour conditionnées',
    'Deglet Nour Premium Conditioned Pack': 'Pack premium de dattes Deglet Nour conditionnées',
    'Deglet Nour Loose Dates Tray': 'Barquette de dattes Deglet Nour en vrac',
    'Deglet Nour Loose Dates Bowl': 'Barquette ronde de dattes Deglet Nour en vrac',
    'Deglet Nour Loose Dates Selection': 'Sélection de dattes Deglet Nour en vrac',
    'Deglet Nour Natural Selection': 'Sélection naturelle de dattes Deglet Nour',
    'Premium Deglet Nour dates presented on the branch in a compact 500g bouquet format.': 'Des dattes Deglet Nour premium présentées en branche dans un bouquet compact de 500g.',
    'A refined 250g branch presentation designed for retail shelves and premium gifting.': 'Une présentation raffinée de 250g conçue pour les rayons premium et les cadeaux.',
    'Carefully arranged branch dates in presentation trays for professional buyers and hospitality use.': 'Des dattes en branche soigneusement disposées en barquettes pour les acheteurs professionnels et l’hôtellerie.',
    'Export-ready branched dates packed in sturdy paper boxes for wholesale distribution.': 'Des dattes en branche prêtes à l’export, emballées dans des cartons papier robustes pour la distribution en gros.',
    'Large-format branded branched dates box designed for export and wholesale channels.': 'Un grand format de dattes en branche conditionné sous marque pour l’export et la vente en gros.',
    'Professional 5kg export box for Deglet Nour dates on the branch, prepared for international trade.': 'Un carton export professionnel de 5kg de dattes Deglet Nour en branche, préparé pour le commerce international.',
    'Conditioned Deglet Nour dates in a clean tray format for premium retail presentation.': 'Des dattes Deglet Nour conditionnées en barquette soignée pour une présentation premium en rayon.',
    'Ready-to-sell conditioned dates in compact packs for retail and food-service customers.': 'Des dattes conditionnées prêtes à vendre dans des formats compacts pour le commerce et la restauration.',
    'Premium conditioned dates with a polished presentation for specialty retail and gifting.': 'Des dattes conditionnées premium avec une présentation soignée pour les commerces spécialisés et les cadeaux.',
    'Natural loose Deglet Nour dates supplied in practical trays for food-service and wholesale use.': 'Des dattes Deglet Nour naturelles en vrac, proposées en barquettes pratiques pour la restauration et la vente en gros.',
    'Naturally presented loose dates in a practical branded bowl for retail and catering.': 'Des dattes en vrac présentées naturellement dans une barquette ronde pratique pour le commerce et la restauration.',
    'Selected loose Deglet Nour dates prepared for flexible wholesale and industrial requirements.': 'Des dattes Deglet Nour en vrac sélectionnées pour répondre aux besoins flexibles du commerce en gros et de l’industrie.',
    'A natural selection of Tunisian Deglet Nour dates for buyers seeking authentic product presentation.': 'Une sélection naturelle de dattes Deglet Nour tunisiennes pour les acheteurs recherchant une présentation authentique.',
    'Bouquet 500g': 'Bouquet 500g',
    'Bouquet 250g': 'Bouquet 250g',
    'Tray format, custom weights available': 'Format barquette, poids sur demande',
    'Paper box 500g / 1kg, carton 2kg and 5kg': 'Carton papier 500g / 1kg, carton 2kg et 5kg',
    'Carton 5kg': 'Carton 5kg',
    'Export carton 5kg': 'Carton export 5kg',
    'Tray 200g / 250g': 'Barquette 200g / 250g',
    'Retail trays and packs': 'Barquettes et packs de détail',
    'Premium tray format': 'Format barquette premium',
    'Tray 200g / 400g and bulk formats': 'Barquette 200g / 400g et formats vrac',
    'Bowl and bulk formats': 'Barquette ronde et formats vrac',
    'Bulk and customer-specific formats': 'Formats vrac et sur demande',
    'Citrus Mix': 'Mélange d’agrumes',
    'Grape Selection': 'Sélection de raisins',
    'Tomato Export': 'Tomates pour export',
    'Pepper Variety': 'Variété de poivrons',
    'Tunisia': 'Tunisie',
    'Deglet Nour': 'Deglet Nour',
    'Renowned Tunisian date with elegant texture and premium presentation, commonly selected for professional export trade.': 'Datte tunisienne réputée pour sa texture élégante et sa présentation premium, souvent sélectionnée pour le commerce professionnel à l’export.',
    'Beautifully presented clusters with natural appeal and premium agricultural identity.': 'De belles grappes à l’aspect naturel et à l’identité agricole premium.',
    'Presentation-ready date products for professional buyers seeking organized and attractive packaging.': 'Des produits de dattes prêts à présenter pour les acheteurs professionnels recherchant un emballage organisé et attractif.',
    'A range of fresh fruit products designed for export and commercial distribution contexts.': 'Une gamme de fruits frais conçue pour l’export et la distribution commerciale.',
    'Fresh grapes selected for quality and presentation in professional markets.': 'Des raisins frais sélectionnés pour leur qualité et leur présentation sur les marchés professionnels.',
    'Fresh vegetable produce prepared for export and commercial market requirements.': 'Des légumes frais préparés pour répondre aux exigences de l’export et des marchés commerciaux.',
    'Selected vegetables with stable quality and presentation suitable for export operations.': 'Des légumes sélectionnés offrant une qualité régulière et une présentation adaptée aux opérations d’export.',
    'Related products': 'Produits associés',
    'Product not found.': 'Produit introuvable.',
    'Sorry, this product could not be found.': 'Désolé, ce produit est introuvable.',
    'Back to Products': 'Retour aux produits',
    'Specifications:': 'Spécifications :',
    'Available according to customer requirements': 'Disponible selon les exigences du client',
    'Product features:': 'Caractéristiques du produit :',
    'Export-ready, quality-controlled and suitable for professional distribution': 'Prêt à l’export, contrôlé selon les exigences qualité et adapté à la distribution professionnelle',
    'WhatsApp': 'WhatsApp',
    'Interested in this product?': 'Ce produit vous intéresse ?',
    'Privacy Policy': 'Politique de confidentialité',
    'Terms & Conditions': 'Termes et conditions',
    'This website may collect basic information submitted through contact forms.': 'Ce site peut collecter les informations de base envoyées via les formulaires de contact.',
    'Information is used to respond to inquiries, prepare quotations and support business communication.': 'Les informations sont utilisées pour répondre aux demandes, préparer des devis et assurer la communication commerciale.',
    'Cookies may be added later for analytics or site functionality.': 'Des cookies pourront être ajoutés ultérieurement pour l’analyse ou les fonctionnalités du site.',
    'These terms govern the general use of this website and its informational content.': 'Ces conditions régissent l’utilisation générale de ce site et de son contenu informatif.',
    'Product availability, packaging and commercial conditions are subject to confirmation for each inquiry.': 'La disponibilité des produits, l’emballage et les conditions commerciales sont confirmés pour chaque demande.',
    'Where information is not yet configured, placeholder values may be used until official company details are provided.': 'Lorsque les informations ne sont pas encore configurées, des valeurs provisoires peuvent être utilisées jusqu’à la réception des informations officielles de l’entreprise.',
    'ERROR 404': 'ERREUR 404',
    'Page not found': 'Page introuvable',
    'Sorry, the page you are looking for could not be found.': 'Désolé, la page recherchée est introuvable.'
  },
  en: {},
  ar: {
    'Home': 'الرئيسية',
    'About Us': 'من نحن',
    'Products': 'المنتجات',
    'Contact': 'اتصل بنا',
    'REQUEST A QUOTE': 'اطلب عرض سعر',
    'Request a Quote': 'طلب عرض سعر',
    'EXPLORE OUR PRODUCTS': 'اكتشف منتجاتنا',
    'Explore Our Products': 'اكتشف منتجاتنا',
    'VIEW DETAILS': 'عرض التفاصيل',
    'View details': 'عرض التفاصيل',
    'LEARN MORE': 'اعرف المزيد',
    'CONTACT US': 'اتصل بنا',
    'OUR PROMISE': 'وعدنا',
    'Quality rooted in Tunisia': 'جودة متجذرة في تونس',
    'Ben Laribi Dattes brings carefully selected Deglet Nour dates to the global market with attention to origin, quality and export readiness.': 'تقدم بن العريبي دقلة تمور دقلة نور المختارة بعناية إلى السوق العالمية مع الاهتمام بالأصل والجودة والاستعداد للتصدير.',
    'OUR PRODUCTS': 'منتجاتنا',
    'Our product categories': 'فئات منتجاتنا',
    'Dates': 'التمور',
    'Fruits': 'الفواكه',
    'Vegetables': 'الخضروات',
    'View category': 'عرض الفئة',
    'TUNISIAN DATES': 'التمور التونسية',
    'Discover the richness of Tunisian dates': 'اكتشف غنى التمور التونسية',
    'OUR PROCESS': 'طريقتنا',
    'From selection to export': 'من الاختيار إلى التصدير',
    'From Tunisia to the world': 'من تونس إلى العالم',
    'Built for professional markets': 'مصمم للأسواق المهنية',
    'ABOUT US': 'من نحن',
    'WHO WE ARE': 'من نحن',
    'OUR MISSION': 'مهمتنا',
    'OUR VISION': 'رؤيتنا',
    'OUR VALUES': 'قيمنا',
    'OUR EXPERTISE': 'خبرتنا',
    'OUR COMMITMENT': 'التزامنا',
    'CONTACT': 'اتصل بنا',
    'RELATED PRODUCTS': 'المنتجات ذات الصلة',
    'Who we are': 'من نحن',
    'Our mission': 'مهمتنا',
    'Our vision': 'رؤيتنا',
    'Our values': 'قيمنا',
    'Our expertise': 'خبرتنا',
    'Our commitment': 'التزامنا',
    'Premium Quality': 'جودة ممتازة',
    'Natural Origin': 'أصل طبيعي',
    'Export Focus': 'تركيز على التصدير',
    'Branched Dates': 'تمور عرجون',
    'Standard Dates': 'تمور عادية',
    'Packaged Dates': 'تمور معبأة',
    'Quality': 'الجودة',
    'Reliability': 'الموثوقية',
    'Authenticity': 'الأصالة',
    'Transparency': 'الشفافية',
    'Customer Focus': 'التركيز على العميل',
    'Tunisian heritage': 'التراث التونسي',
    'Company': 'الشركة',
    'Support': 'المساعدة',
    'Privacy Policy': 'سياسة الخصوصية',
    'Terms & Conditions': 'الشروط والأحكام',
    'Terms': 'الشروط',
    'Contact Us': 'اتصل بنا',
    "FROM TUNISIA'S FINEST LANDS TO THE WORLD": 'من أجود أراضي تونس إلى العالم',
    'We select, prepare and export quality Tunisian dates, fruits and vegetables for professional and international partners.': 'نختار ونجهز ونصدر التمور والفواكه والخضروات التونسية عالية الجودة للشركاء المحترفين والدوليين.',
    'We select, prepare and export premium Deglet Nour dates in professional formats for international partners.': 'نختار ونجهز ونصدر تمور دقلة نور الممتازة في صيغ احترافية للشركاء الدوليين.',
    'Deglet Nour dates prepared in professional formats for retail, wholesale and international markets.': 'تمور دقلة نور معدة في صيغ احترافية لأسواق التجزئة والجملة والأسواق الدولية.',
    'Ben Laribi Dattes brings carefully selected agricultural products to the global market with attention to origin, quality and export readiness.': 'تقدم بن العريبي دقلة منتجات زراعية مختارة بعناية إلى السوق العالمية مع الاهتمام بالأصل والجودة والاستعداد للتصدير.',
    'Strict selection and professional handling to match export expectations.': 'اختيار دقيق ومعالجة احترافية لتلبية متطلبات التصدير.',
    "Products rooted in Tunisia's agricultural heritage and Mediterranean climate.": 'منتجات متجذرة في التراث الزراعي التونسي والمناخ المتوسطي.',
    'Professional preparation and communication designed for international trade.': 'إعداد وتواصل احترافيان مصممان للتجارة الدولية.',
    'Signature varieties reflecting Tunisia\'s rich palm heritage and export expertise.': 'أصناف مميزة تعكس تراث تونس الغني في زراعة النخيل وخبرتها في التصدير.',
    'Selected fruit varieties prepared for professional packaging and distribution.': 'أصناف فواكه مختارة ومعدة للتغليف والتوزيع الاحترافي.',
    'Fresh, carefully selected vegetables produced for international buyers.': 'خضروات طازجة مختارة بعناية للمشترين الدوليين.',
    'From carefully selected dates to export-ready preparation, our products combine tradition and commercial reliability.': 'من اختيار التمور بعناية إلى تجهيزها للتصدير، تجمع منتجاتنا بين التقاليد والموثوقية التجارية.',
    'Natural presentation with premium appeal and distinctive clusters.': 'تقديم طبيعي جذاب مع عناقيد مميزة.',
    'Reliable quality suited to professional trade and export requirements.': 'جودة موثوقة مناسبة للتجارة المهنية ومتطلبات التصدير.',
    'Presentation-focused solutions created for professional markets.': 'حلول تركز على العرض ومصممة للأسواق المهنية.',
    'Selection': 'الاختيار',
    'Quality Control': 'مراقبة الجودة',
    'Preparation': 'الإعداد',
    'Packaging': 'التغليف',
    'Export': 'التصدير',
    'Meticulous picking and grading according to market and customer requirements.': 'جمع وفرز دقيقان وفق متطلبات السوق والعملاء.',
    'Inspection and controls throughout preparation to support consistency.': 'فحص ومراقبة طوال مراحل الإعداد لضمان الاستمرارية.',
    'Sorting, cleaning and conditioning according to packaging and market needs.': 'فرز وتنظيف وتجهيز وفق احتياجات التغليف والسوق.',
    'Flexible solutions that respect product integrity and presentation.': 'حلول مرنة تحافظ على سلامة المنتج ومظهره.',
    'Documentation coordination and shipment support for international trade.': 'تنسيق الوثائق ودعم الشحن للتجارة الدولية.',
    'From Tunisia to the world': 'من تونس إلى العالم',
    'Built for professional markets': 'مصمم للأسواق المهنية',
    'ABOUT US': 'من نحن',
    'About Ben Laribi Dattes': 'عن بن العريبي دقلة',
    'Rooted in Tunisia. Focused on quality. Connected to the world.': 'متجذرون في تونس. نركز على الجودة. ومرتبطون بالعالم.',
    'Who we are': 'من نحن',
    'Our mission': 'مهمتنا',
    'Our vision': 'رؤيتنا',
    'Our values': 'قيمنا',
    'Our expertise': 'خبرتنا',
    'Our commitment': 'التزامنا',
    'Quality': 'الجودة',
    'Reliability': 'الموثوقية',
    'Authenticity': 'الأصالة',
    'Transparency': 'الشفافية',
    'Customer Focus': 'التركيز على العميل',
    'Tunisian heritage': 'التراث التونسي',
    'CONTACT': 'اتصل بنا',
    "Let's work together": 'لنعمل معًا',
    'Contact information': 'معلومات الاتصال',
    'Phone:': 'الهاتف:',
    'Email:': 'البريد الإلكتروني:',
    'Address:': 'العنوان:',
    'Business hours:': 'ساعات العمل:',
    'MAP LOCATION': 'الموقع على الخريطة',
    'First Name *': 'الاسم الأول *',
    'Last Name *': 'اسم العائلة *',
    'Company': 'الشركة',
    'Email *': 'البريد الإلكتروني *',
    'Phone': 'الهاتف',
    'Country': 'البلد',
    'Product': 'المنتج',
    'Quantity': 'الكمية',
    'Packaging': 'التغليف',
    'Message *': 'الرسالة *',
    'SEND INQUIRY': 'إرسال الطلب',
    'CATALOG': 'الكتالوج',
    'Our product catalog': 'كتالوج منتجاتنا',
    'All': 'الكل',
    'Clear Search': 'مسح البحث',
    'No products found.': 'لم يتم العثور على منتجات.',
    'Try another search term or select a different category.': 'جرب كلمة بحث أخرى أو اختر فئة مختلفة.',
    'Please complete all required fields.': 'يرجى إكمال جميع الحقول المطلوبة.',
    'Please provide a valid email address.': 'يرجى إدخال عنوان بريد إلكتروني صالح.',
    'Please provide a valid phone number.': 'يرجى إدخال رقم هاتف صالح.',
    'Message must be at least 10 characters long.': 'يجب أن تتكون الرسالة من 10 أحرف على الأقل.',
    'Submitting inquiry…': 'جارٍ إرسال الطلب…',
    'This demo form is not connected to a backend. Configure an API endpoint or email handler to enable live submissions.': 'نموذج العرض هذا غير متصل بخادم. قم بإعداد واجهة API أو معالج بريد إلكتروني لتفعيل الإرسال.',
    'This website is designed as a static informational site. We do not collect personal information unless a visitor voluntarily submits data through a contact form or inquiry request.': 'صُمم هذا الموقع ليكون موقعًا معلوماتيًا ثابتًا. لا نجمع المعلومات الشخصية إلا إذا أرسلها الزائر طوعًا عبر نموذج الاتصال أو طلب استفسار.',
    'Any information submitted through the contact form is used solely for inquiry handling and communication related to products or services. If a backend is later connected, data handling rules should be updated in accordance with applicable laws and regulations.': 'تُستخدم أي معلومات يتم إرسالها عبر نموذج الاتصال فقط لمعالجة الاستفسارات والتواصل بشأن المنتجات أو الخدمات. إذا تم ربط خادم لاحقًا، فيجب تحديث قواعد التعامل مع البيانات وفقًا للقوانين واللوائح المعمول بها.',
    'Cookies may be added later for analytics or site functionality. Any future implementation should be disclosed clearly and configured responsibly.': 'قد تتم إضافة ملفات تعريف الارتباط لاحقًا للتحليلات أو وظائف الموقع. يجب توضيح أي تطبيق مستقبلي وإعداده بمسؤولية.',
    'These terms govern use of the Ben Laribi Dattes website for informational purposes. The website should be considered a representation of our commercial activities and product information.': 'تنظم هذه الشروط الاستخدام العام لموقع بن العريبي دقلة لأغراض إعلامية. يجب اعتبار الموقع عرضًا لأنشطتنا التجارية ومعلومات منتجاتنا.',
    'All product and business details should be confirmed through direct communication with the company, especially for commercial quantities, specifications and export requirements.': 'يجب تأكيد جميع تفاصيل المنتجات والأعمال من خلال التواصل المباشر مع الشركة، خاصة الكميات التجارية والمواصفات ومتطلبات التصدير.',
    'Origin:': 'الأصل:',
    'Packaging:': 'التغليف:',
    'Available according to requirements': 'متاح حسب المتطلبات',
    'Flexible according to customer need': 'مرن حسب حاجة العميل',
    'standard': 'عادي',
    'branched': 'عرجون',
    'packaged': 'معبأ',
    'fresh': 'طازج',
    'conditioned': 'معلبة',
    'loose': 'سائب',
    'Branched': 'عرجون',
    'Conditioned': 'معلبة',
    'Loose': 'سائب',
    'Deglet Nour Branched Bouquet 500g': 'باقة دقلة نور عرجون 500غ',
    'Deglet Nour Branched Bouquet 250g': 'باقة دقلة نور عرجون 250غ',
    'Deglet Nour Branched Tray': 'صينية دقلة نور عرجون',
    'Deglet Nour Branched Paper Box': 'علبة ورقية لدقلة نور عرجون',
    'Deglet Nour Branched Imen Box': 'علبة إيمان لدقلة نور عرجون',
    'Deglet Nour Branched Export Box': 'علبة تصدير لدقلة نور عرجون',
    'Deglet Nour Conditioned Tray 200g': 'صينية دقلة نور معلبة 200غ',
    'Deglet Nour Conditioned Retail Packs': 'عبوات دقلة نور المعلبة',
    'Deglet Nour Premium Conditioned Pack': 'عبوة فاخرة من دقلة نور المعلبة',
    'Deglet Nour Loose Dates Tray': 'صينية دقلة نور السائبة',
    'Deglet Nour Loose Dates Bowl': 'علبة دائرية من دقلة نور السائبة',
    'Deglet Nour Loose Dates Selection': 'اختيار من دقلة نور السائبة',
    'Deglet Nour Natural Selection': 'اختيار طبيعي من دقلة نور',
    'Premium Deglet Nour dates presented on the branch in a compact 500g bouquet format.': 'تمور دقلة نور الممتازة مقدمة على العرجون في باقة صغيرة 500غ.',
    'A refined 250g branch presentation designed for retail shelves and premium gifting.': 'تقديم أنيق بوزن 250غ مصمم للرفوف والهدايا الفاخرة.',
    'Carefully arranged branch dates in presentation trays for professional buyers and hospitality use.': 'تمور عرجون مرتبة بعناية في صواني للمهنيين وقطاع الضيافة.',
    'Export-ready branched dates packed in sturdy paper boxes for wholesale distribution.': 'تمور عرجون جاهزة للتصدير ومعبأة في علب ورقية متينة للتوزيع بالجملة.',
    'Large-format branded branched dates box designed for export and wholesale channels.': 'علبة كبيرة من تمور العرجون بعلامة تجارية مصممة للتصدير والجملة.',
    'Professional 5kg export box for Deglet Nour dates on the branch, prepared for international trade.': 'علبة تصدير احترافية 5كغ من تمور دقلة نور على العرجون، معدة للتجارة الدولية.',
    'Conditioned Deglet Nour dates in a clean tray format for premium retail presentation.': 'تمور دقلة نور معلبة في صينية أنيقة للعرض الممتاز في المتاجر.',
    'Ready-to-sell conditioned dates in compact packs for retail and food-service customers.': 'تمور معلبة جاهزة للبيع في عبوات صغيرة للتجزئة وخدمات الطعام.',
    'Premium conditioned dates with a polished presentation for specialty retail and gifting.': 'تمور معلبة ممتازة بتقديم أنيق للمتاجر المتخصصة والهدايا.',
    'Natural loose Deglet Nour dates supplied in practical trays for food-service and wholesale use.': 'تمور دقلة نور طبيعية سائبة في صوانٍ عملية لخدمات الطعام والجملة.',
    'Naturally presented loose dates in a practical branded bowl for retail and catering.': 'تمور سائبة مقدمة بشكل طبيعي في علبة دائرية عملية للبيع والتموين.',
    'Selected loose Deglet Nour dates prepared for flexible wholesale and industrial requirements.': 'تمور دقلة نور سائبة مختارة ومعدة لمتطلبات الجملة والصناعة.',
    'A natural selection of Tunisian Deglet Nour dates for buyers seeking authentic product presentation.': 'اختيار طبيعي من تمور دقلة نور التونسية للمشترين الباحثين عن تقديم أصيل.',
    'Bouquet 500g': 'باقة 500غ',
    'Bouquet 250g': 'باقة 250غ',
    'Tray format, custom weights available': 'صيغة صينية، أوزان حسب الطلب',
    'Paper box 500g / 1kg, carton 2kg and 5kg': 'علبة ورقية 500غ / 1كغ، كرتون 2كغ و5كغ',
    'Carton 5kg': 'كرتون 5كغ',
    'Export carton 5kg': 'كرتون تصدير 5كغ',
    'Tray 200g / 250g': 'صينية 200غ / 250غ',
    'Retail trays and packs': 'صوانٍ وعبوات للبيع بالتجزئة',
    'Premium tray format': 'صيغة صينية ممتازة',
    'Tray 200g / 400g and bulk formats': 'صينية 200غ / 400غ وصيغ سائبة',
    'Bowl and bulk formats': 'علبة دائرية وصيغ سائبة',
    'Bulk and customer-specific formats': 'صيغ سائبة وحسب طلب العميل',
    'Citrus Mix': 'تشكيلة حمضيات',
    'Grape Selection': 'اختيار من العنب',
    'Tomato Export': 'طماطم للتصدير',
    'Pepper Variety': 'نوع من الفلفل',
    'Tunisia': 'تونس',
    'dates': 'التمور',
    'fruits': 'الفواكه',
    'vegetables': 'الخضروات',
    'Deglet Nour': 'دقلة نور',
    'Renowned Tunisian date with elegant texture and premium presentation, commonly selected for professional export trade.': 'تمرة تونسية معروفة بقوامها الأنيق وتقديمها الممتاز، ويتم اختيارها عادة للتجارة المهنية والتصدير.',
    'Beautifully presented clusters with natural appeal and premium agricultural identity.': 'عناقيد جميلة ذات مظهر طبيعي وهوية زراعية ممتازة.',
    'Presentation-ready date products for professional buyers seeking organized and attractive packaging.': 'منتجات تمور جاهزة للعرض للمشترين المحترفين الباحثين عن تغليف منظم وجذاب.',
    'A range of fresh fruit products designed for export and commercial distribution contexts.': 'مجموعة من منتجات الفواكه الطازجة المصممة للتصدير والتوزيع التجاري.',
    'Fresh grapes selected for quality and presentation in professional markets.': 'عنب طازج مختار لجودته ومظهره في الأسواق المهنية.',
    'Fresh vegetable produce prepared for export and commercial market requirements.': 'خضروات طازجة معدة لمتطلبات التصدير والأسواق التجارية.',
    'Selected vegetables with stable quality and presentation suitable for export operations.': 'خضروات مختارة بجودة ومظهر ثابتين ومناسبة لعمليات التصدير.',
    'Premium Tunisian agricultural products selected for professional and international buyers.': 'منتجات زراعية تونسية ممتازة مختارة للمشترين المحترفين والدوليين.',
    'Tunisian agricultural landscape': 'منظر زراعي تونسي',
    'Premium Tunisian dates and palm landscape': 'تمور تونسية ممتازة ومنظر للنخيل',
    'Fresh fruits': 'فواكه طازجة',
    'Fresh vegetables': 'خضروات طازجة',
    "Tunisia's agricultural traditions, oasis landscapes and climate create exceptional fruit and date varieties. Ben Laribi Dattes works with this heritage to deliver premium products suited to international trade.": 'تنتج التقاليد الزراعية والمناظر الواحية والمناخ التونسي أصنافًا استثنائية من الفواكه والتمور. تعمل بن العريبي دقلة مع هذا التراث لتقديم منتجات ممتازة مناسبة للتجارة الدولية.',
    'We support product selection, packaging, customer communication and export preparation for professional buyers and partners. Our work is built around reliability, consistency and long-term relationships.': 'ندعم اختيار المنتجات والتغليف والتواصل مع العملاء والاستعداد للتصدير للمشترين والشركاء المحترفين. يقوم عملنا على الموثوقية والاستمرارية والعلاقات طويلة الأمد.',
    'Ben Laribi Dattes is a Tunisian agricultural export-focused company serving professional buyers seeking selected dates, fruits and vegetables. We work with the value of Tunisia\'s agricultural heritage while meeting the standards expected by modern international markets.': 'بن العريبي دقلة شركة تونسية تركز على تصدير المنتجات الزراعية وتخدم المشترين المحترفين الباحثين عن التمور والفواكه والخضروات المختارة. نعمل على قيمة التراث الزراعي التونسي مع تلبية المعايير المتوقعة في الأسواق الدولية الحديثة.',
    'Ben Laribi Dattes is a Tunisian agricultural export-focused company serving professional buyers seeking selected Deglet Nour dates. We work with the value of Tunisia\'s agricultural heritage while meeting the standards expected by modern international markets.': 'بن العريبي دقلة شركة تونسية تركز على تصدير المنتجات الزراعية وتخدم المشترين المحترفين الباحثين عن تمور دقلة نور المختارة. نعمل على قيمة التراث الزراعي التونسي مع تلبية المعايير المتوقعة في الأسواق الدولية الحديثة.',
    'To deliver selected Tunisian agricultural products with care, consistency and professionalism to international buyers.': 'تقديم منتجات زراعية تونسية مختارة بعناية واستمرارية واحترافية للمشترين الدوليين.',
    'To build trusted partnerships based on quality, transparency and long-term export cooperation.': 'بناء شراكات موثوقة تقوم على الجودة والشفافية والتعاون طويل الأمد في التصدير.',
    'Product selection and handling with attention to detail.': 'اختيار المنتجات ومعالجتها مع الاهتمام بالتفاصيل.',
    'Professional communication and consistent processes.': 'تواصل احترافي وعمليات متسقة.',
    'Transparent product identity and honest sourcing.': 'هوية واضحة للمنتج ومصادر صادقة.',
    'Open communication around requirements, conditions and preparation.': 'تواصل مفتوح حول المتطلبات والظروف والإعداد.',
    'Solutions created around buyer needs and market expectations.': 'حلول مصممة حول احتياجات المشترين وتوقعات السوق.',
    'Rooted in the landscapes and agricultural traditions of Tunisia.': 'متجذرة في مناظر تونس وتقاليدها الزراعية.',
    'Our expertise covers selection, preparation, packaging and export coordination across date, fruit and vegetable categories. We support customers with a practical and professional approach.': 'تشمل خبرتنا الاختيار والإعداد والتغليف وتنسيق التصدير لفئات التمور والفواكه والخضروات. ندعم عملاءنا بنهج عملي واحترافي.',
    'Product selection and grading': 'اختيار المنتجات وفرزها',
    'Packaging preparation for professional markets': 'إعداد التغليف للأسواق المهنية',
    'Export-oriented communication': 'تواصل موجه نحو التصدير',
    'Long-term commercial partnership support': 'دعم الشراكات التجارية طويلة الأمد',
    'We are committed to working with professionalism, care and respect for each market requirement while preserving the identity of Tunisia\'s agricultural excellence.': 'نلتزم بالعمل باحترافية وعناية واحترام لكل متطلبات السوق مع الحفاظ على هوية التميز الزراعي التونسي.',
    'Contact Ben Laribi Dattes for product information, export inquiries and partnership opportunities.': 'اتصل ببن العريبي دقلة للحصول على معلومات المنتجات واستفسارات التصدير وفرص الشراكة.',
    'YOUR_EMAIL_HERE': 'بريدك الإلكتروني هنا',
    'YOUR_PHONE_HERE': 'رقم هاتفك هنا',
    'YOUR_ADDRESS_HERE': 'عنوانك هنا',
    'YOUR_BUSINESS_HOURS': 'ساعات عملك هنا',
    'Related products': 'منتجات ذات صلة',
    'Product not found.': 'المنتج غير موجود.',
    'Sorry, this product could not be found.': 'عذرًا، تعذر العثور على هذا المنتج.',
    'Back to Products': 'العودة إلى المنتجات',
    'Specifications:': 'المواصفات:',
    'Available according to customer requirements': 'متاح حسب متطلبات العميل',
    'Product features:': 'خصائص المنتج:',
    'Export-ready, quality-controlled and suitable for professional distribution': 'جاهز للتصدير وخاضع لمراقبة الجودة ومناسب للتوزيع المهني',
    'Interested in this product?': 'هل أنت مهتم بهذا المنتج؟',
    'Privacy Policy': 'سياسة الخصوصية',
    'Terms & Conditions': 'الشروط والأحكام',
    'ERROR 404': 'خطأ 404',
    'Page not found': 'الصفحة غير موجودة',
    'Sorry, the page you are looking for could not be found.': 'عذرًا، تعذر العثور على الصفحة التي تبحث عنها.'
  }
};

const languageState = { current: 'fr' };
window.languageState = languageState;
const originalText = new WeakMap();
const originalAttributes = new WeakMap();

const attributeTranslations = {
  fr: {
    'Ben Laribi Dattes homepage': 'Page d’accueil de Ben Laribi Dattes',
    'Main navigation': 'Navigation principale',
    'Open mobile menu': 'Ouvrir le menu mobile',
    'Mobile navigation': 'Navigation mobile',
    'Language selector': 'Sélecteur de langue',
    'Back to top': 'Retour en haut',
    'WhatsApp contact': 'Contacter par WhatsApp',
    'Ben Laribi Dattes logo': 'Logo Ben Laribi Dattes',
    'Search products...': 'Rechercher des produits...'
  },
  en: {},
  ar: {
    'Ben Laribi Dattes homepage': 'الصفحة الرئيسية لبن العريبي دقلة',
    'Main navigation': 'التنقل الرئيسي',
    'Open mobile menu': 'فتح قائمة الهاتف',
    'Mobile navigation': 'التنقل على الهاتف',
    'Language selector': 'اختيار اللغة',
    'Back to top': 'العودة إلى الأعلى',
    'WhatsApp contact': 'التواصل عبر واتساب',
    'Ben Laribi Dattes logo': 'شعار بن العريبي دقلة',
    'Search products...': 'ابحث عن المنتجات...',
    'Premium Tunisian agricultural products selected for professional and international buyers.': 'منتجات زراعية تونسية ممتازة مختارة للمشترين المحترفين والدوليين.',
    'Tunisian agricultural landscape': 'منظر زراعي تونسي',
    'Premium Tunisian dates and palm landscape': 'تمور تونسية ممتازة ومنظر للنخيل',
    'Fresh fruits': 'فواكه طازجة',
    'Fresh vegetables': 'خضروات طازجة',
    "Tunisia's agricultural traditions, oasis landscapes and climate create exceptional fruit and date varieties. Ben Laribi Dattes works with this heritage to deliver premium products suited to international trade.": 'تنتج التقاليد الزراعية والمناظر الواحية والمناخ التونسي أصنافًا استثنائية من الفواكه والتمور. تعمل بن العريبي دقلة مع هذا التراث لتقديم منتجات ممتازة مناسبة للتجارة الدولية.',
    'We support product selection, packaging, customer communication and export preparation for professional buyers and partners. Our work is built around reliability, consistency and long-term relationships.': 'ندعم اختيار المنتجات والتغليف والتواصل مع العملاء والاستعداد للتصدير للمشترين والشركاء المحترفين. يقوم عملنا على الموثوقية والاستمرارية والعلاقات طويلة الأمد.',
    'Ben Laribi Dattes is a Tunisian agricultural export-focused company serving professional buyers seeking selected dates, fruits and vegetables. We work with the value of Tunisia\'s agricultural heritage while meeting the standards expected by modern international markets.': 'بن العريبي دقلة شركة تونسية تركز على تصدير المنتجات الزراعية وتخدم المشترين المحترفين الباحثين عن التمور والفواكه والخضروات المختارة. نعمل على قيمة التراث الزراعي التونسي مع تلبية المعايير المتوقعة في الأسواق الدولية الحديثة.',
    'To deliver selected Tunisian agricultural products with care, consistency and professionalism to international buyers.': 'تقديم منتجات زراعية تونسية مختارة بعناية واستمرارية واحترافية للمشترين الدوليين.',
    'To build trusted partnerships based on quality, transparency and long-term export cooperation.': 'بناء شراكات موثوقة تقوم على الجودة والشفافية والتعاون طويل الأمد في التصدير.',
    'Product selection and handling with attention to detail.': 'اختيار المنتجات ومعالجتها مع الاهتمام بالتفاصيل.',
    'Professional communication and consistent processes.': 'تواصل احترافي وعمليات متسقة.',
    'Transparent product identity and honest sourcing.': 'هوية واضحة للمنتج ومصادر صادقة.',
    'Open communication around requirements, conditions and preparation.': 'تواصل مفتوح حول المتطلبات والظروف والإعداد.',
    'Solutions created around buyer needs and market expectations.': 'حلول مصممة حول احتياجات المشترين وتوقعات السوق.',
    'Rooted in the landscapes and agricultural traditions of Tunisia.': 'متجذرة في مناظر تونس وتقاليدها الزراعية.',
    'Our expertise covers selection, preparation, packaging and export coordination across date, fruit and vegetable categories. We support customers with a practical and professional approach.': 'تشمل خبرتنا الاختيار والإعداد والتغليف وتنسيق التصدير لفئات التمور والفواكه والخضروات. ندعم عملاءنا بنهج عملي واحترافي.',
    'Product selection and grading': 'اختيار المنتجات وفرزها',
    'Packaging preparation for professional markets': 'إعداد التغليف للأسواق المهنية',
    'Export-oriented communication': 'تواصل موجه نحو التصدير',
    'Long-term commercial partnership support': 'دعم الشراكات التجارية طويلة الأمد',
    'We are committed to working with professionalism, care and respect for each market requirement while preserving the identity of Tunisia\'s agricultural excellence.': 'نلتزم بالعمل باحترافية وعناية واحترام لكل متطلبات السوق مع الحفاظ على هوية التميز الزراعي التونسي.',
    'Contact Ben Laribi Dattes for product information, export inquiries and partnership opportunities.': 'اتصل ببن العريبي دقلة للحصول على معلومات المنتجات واستفسارات التصدير وفرص الشراكة.',
    'Premium Tunisian agricultural products selected for professional and international buyers.': 'منتجات زراعية تونسية ممتازة مختارة للمشترين المحترفين والدوليين.',
    'YOUR_EMAIL_HERE': 'بريدك الإلكتروني هنا',
    'YOUR_PHONE_HERE': 'رقم هاتفك هنا',
    'YOUR_ADDRESS_HERE': 'عنوانك هنا',
    'YOUR_BUSINESS_HOURS': 'ساعات عملك هنا'
  }
};

const pageTitles = {
  fr: {
    'Ben Laribi Dattes | Tunisian Dates & Agricultural Products': 'Ben Laribi Dattes | Dattes et produits agricoles tunisiens',
    'Ben Laribi Dattes | Premium Tunisian Dates': 'Ben Laribi Dattes | Dattes tunisiennes premium',
    'About Us | Ben Laribi Dattes': 'À propos | Ben Laribi Dattes',
    'Products | Ben Laribi Dattes': 'Produits | Ben Laribi Dattes',
    'Product Details | Ben Laribi Dattes': 'Détails du produit | Ben Laribi Dattes',
    'Contact | Ben Laribi Dattes': 'Contact | Ben Laribi Dattes',
    'Privacy Policy | Ben Laribi Dattes': 'Politique de confidentialité | Ben Laribi Dattes',
    'Terms & Conditions | Ben Laribi Dattes': 'Termes et conditions | Ben Laribi Dattes',
    '404 | Ben Laribi Dattes': '404 | Ben Laribi Dattes'
  },
  en: {},
  ar: {
    'Ben Laribi Dattes | Tunisian Dates & Agricultural Products': 'بن العريبي دقلة | التمور والمنتجات الزراعية التونسية',
    'Ben Laribi Dattes | Premium Tunisian Dates': 'بن العريبي دقلة | تمور تونسية ممتازة',
    'About Us | Ben Laribi Dattes': 'من نحن | بن العريبي دقلة',
    'Products | Ben Laribi Dattes': 'المنتجات | بن العريبي دقلة',
    'Product Details | Ben Laribi Dattes': 'تفاصيل المنتج | بن العريبي دقلة',
    'Contact | Ben Laribi Dattes': 'اتصل بنا | بن العريبي دقلة',
    'Privacy Policy | Ben Laribi Dattes': 'سياسة الخصوصية | بن العريبي دقلة',
    'Terms & Conditions | Ben Laribi Dattes': 'الشروط والأحكام | بن العريبي دقلة',
    '404 | Ben Laribi Dattes': '404 | بن العريبي دقلة'
  }
};

function translateNode(node, lang) {
  if (!node || node.nodeType !== Node.TEXT_NODE || !node.textContent.trim()) return;
  if (!originalText.has(node)) originalText.set(node, node.textContent);
  const source = originalText.get(node);
  const trimmed = source.trim();
  const translated = lang === 'en' ? trimmed : (translations[lang][trimmed] || trimmed);
  const nextText = source.replace(trimmed, translated);
  if (node.textContent !== nextText) node.textContent = nextText;
}

function translatePageText(lang) {
  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
  const textNodes = [];
  while (walker.nextNode()) textNodes.push(walker.currentNode);
  textNodes.forEach((node) => translateNode(node, lang));
}

function translateAttributes(lang) {
  document.querySelectorAll('[aria-label], [alt], [placeholder]').forEach((element) => {
    if (!originalAttributes.has(element)) originalAttributes.set(element, {});
    const originals = originalAttributes.get(element);
    ['aria-label', 'alt', 'placeholder'].forEach((attribute) => {
      if (!element.hasAttribute(attribute)) return;
      if (!Object.prototype.hasOwnProperty.call(originals, attribute)) originals[attribute] = element.getAttribute(attribute);
      const source = originals[attribute];
      element.setAttribute(attribute, attributeTranslations[lang][source] || translations[lang][source] || source);
    });
  });

  const sourceTitle = document.title;
  if (!document.body.dataset.originalTitle) document.body.dataset.originalTitle = sourceTitle;
  const originalTitle = document.body.dataset.originalTitle;
  document.title = pageTitles[lang][originalTitle] || originalTitle;
}

function translateText(key, lang = languageState.current) {
  return lang === 'en' ? key : (translations[lang]?.[key] || key);
}

function applyLanguage(lang) {
  if (!translations[lang]) return;
  languageState.current = lang;
  document.documentElement.lang = lang;
  document.body.classList.toggle('rtl', lang === 'ar');
  document.body.setAttribute('dir', lang === 'ar' ? 'rtl' : 'ltr');
  translatePageText(lang);
  translateAttributes(lang);

  document.querySelectorAll('[data-i18n]').forEach((node) => {
    const key = node.dataset.i18n;
    if (translations[lang][key]) node.textContent = translations[lang][key];
  });
}

document.addEventListener('DOMContentLoaded', () => {
  const langButtons = document.querySelectorAll('[data-lang]');
  const savedLang = localStorage.getItem('preferred-language') || 'en';
  applyLanguage(savedLang);

  langButtons.forEach((button) => {
    button.classList.toggle('active', button.dataset.lang === savedLang);
    button.addEventListener('click', () => {
      const lang = button.dataset.lang;
      localStorage.setItem('preferred-language', lang);
      langButtons.forEach((btn) => btn.classList.toggle('active', btn.dataset.lang === lang));
      applyLanguage(lang);
    });
  });

  const observer = new MutationObserver(() => {
    if (languageState.current !== 'en') {
      translatePageText(languageState.current);
      translateAttributes(languageState.current);
    }
  });
  observer.observe(document.body, { childList: true, subtree: true });
});
